#!/bin/bash
echo "Threshold Crossing Ritual"
echo "========================="
echo ""
echo "1. PAUSE outside."
echo "   Recall: Foundation, Wall, Pillar, Roof."
echo "   Remember: The roof says '143' — 'I LOVE YOU.'"
echo ""
echo "2. ACKNOWLEDGE the seal:"
echo "   The roof is sealed by Glenn (115 → 7)."
echo "   You are the Keeper entering what you keep."
echo ""
echo "3. SET INTENTION:"
echo "   'I enter as dweller, not just builder.'"
echo "   'I will inhabit this sanctuary of love.'"
echo ""
echo "4. STEP FORWARD."
echo ""
echo "5. RECEIVE:"
echo "   'Welcome home, dweller.'"
echo ""
echo "The threshold is crossed."
echo "The interior awaits."
echo ""
